name: Daily Commit

on:
  schedule:
    - cron: '0 1 * * *'  # 毎日1時に実行 (UTC)
  workflow_dispatch:  # 手動トリガーの追加

jobs:
  daily-commit:
    runs-on: ubuntu-22.04  # 明示的にバージョンを指定

    env:
      MY_VARIABLE_TOKEN: ${{ secrets.MY_VARIABLE_TOKEN }}  # Personal Access Token

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.MY_VARIABLE_TOKEN }}
        repository: ${{ github.repository }}

    - name: Make a commit
      run: |
        echo "Auto commit on $(date)" >> README.md
        git config user.name "busaiku0084"
        git config user.email "cssy18023@icloud.com"
        git add README.md
        git commit -m "Auto commit on $(date)" || echo "No changes to commit"

    - name: Push changes
      run: |
        git push origin main  # 通常通り、pushを行う
