name: Daily Commit

on:
  schedule:
    - cron: '0 1 * * *'  # 毎日1時に実行 (UTC)
  workflow_dispatch:  # 手動トリガーの追加

jobs:
  daily-commit:
    runs-on: ubuntu-22.04  # 明示的にバージョンを指定

    env:
      MY_VARIABLE_TOKEN: ${{ secrets.TOKEN_FOR_PUSH }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Make a commit
      run: |
        echo "Auto commit on $(date)" >> README.md
        git config user.name "busaiku0084"
        git config user.email "cssy18023@icloud.com"
        git add README.md
        git commit -m "Auto commit on $(date)" || echo "No changes to commit"

    - name: Push changes
      run: |
        git remote set-url origin https://x-access-token:${MY_VARIABLE_TOKEN}@github.com/${{ github.repository }}.git
        git push origin main
